// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxwBD112cWZ9CWhcEOYe-8a1bVv6M7Crw',
    appId: '1:53074370433:web:8cacd39882a42fe9fb5280',
    messagingSenderId: '53074370433',
    projectId: 'idnphonerent',
    authDomain: 'idnphonerent.firebaseapp.com',
    storageBucket: 'idnphonerent.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8o84MD2e5xyYH_kDWP7Xe0n_NVwcB-GY',
    appId: '1:53074370433:android:c247a1d4522fff1efb5280',
    messagingSenderId: '53074370433',
    projectId: 'idnphonerent',
    storageBucket: 'idnphonerent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSHOVpI4GqiZkoazEErQ5jTetP_7WMX5s',
    appId: '1:53074370433:ios:6e61453ee4d218c1fb5280',
    messagingSenderId: '53074370433',
    projectId: 'idnphonerent',
    storageBucket: 'idnphonerent.firebasestorage.app',
    iosBundleId: 'com.example.deviceManager',
  );
}
